import { type FormEvent, useState } from 'react';
import { FaArrowRight, FaCode, FaLayerGroup, FaMobileAlt, FaRegLightbulb, FaRobot, FaServer, FaWhatsapp } from 'react-icons/fa';
import { StudioNavbar } from '../../components/studio/StudioNavbar';
import { studioContent, type StudioLanguage } from '../../data/studioContent';
import styles from './StudioLanding.module.css';

const productMeta = [['ACITA', '/assets/images/acita/1.png', 'purple'], ['ACATA', '/assets/images/acata/1.png', 'orange'], ['KEPCHU', '/assets/images/kepchu/1.png', 'blue'], ['PROGRAMAR WHATSAPP', '/assets/images/programar-whatsapp/1.png', 'green']] as const;
const serviceIcons = [FaRegLightbulb, FaLayerGroup, FaCode, FaMobileAlt, FaServer, FaRobot];

export function StudioLanding() {
  const [language, setLanguage] = useState<StudioLanguage>('es');
  const [form, setForm] = useState({ name: '', email: '', message: '' });
  const copy = studioContent[language];
  const submitContact = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const message = language === 'es'
      ? `Hola, soy ${form.name}.%0AEmail: ${form.email}.%0A%0AMe interesa: ${form.message}`
      : `Hi, I'm ${form.name}.%0AEmail: ${form.email}.%0A%0AI'm interested in: ${form.message}`;
    window.open(`https://wa.me/51910486668?text=${message}`, '_blank', 'noopener,noreferrer');
  };
  return <main>
    <StudioNavbar language={language} onLanguageChange={setLanguage} labels={copy.nav} talk={copy.talk} />
    <section id="inicio" className={styles.hero}><div className={styles.heroGrid} /><div className={styles.heroContent}><div className={styles.heroCopy}><p className={styles.kicker}><i /> {copy.hero.eyebrow}</p><h1>{copy.hero.title}</h1><p className={styles.lead}>{copy.hero.lead}</p><div className={styles.heroActions}><a href="#contacto" className={styles.primaryButton}>{copy.hero.primary} <FaArrowRight /></a><a href="#productos" className={styles.textButton}>{copy.hero.secondary} <span>↓</span></a></div></div><div className={styles.heroVisual}><div className={styles.orbit} /><div className={`${styles.floatingCard} ${styles.cardOne}`}><span className={styles.miniIcon}>✦</span><div><b>{copy.hero.cardOne[0]}</b><small>{copy.hero.cardOne[1]}</small></div></div><div className={`${styles.floatingCard} ${styles.cardTwo}`}><span className={styles.greenDot} /><div><b>{copy.hero.cardTwo[0]}</b><small>{copy.hero.cardTwo[1]}</small></div></div><div className={styles.productSphere}><div className={styles.sphereGlow} /><img src="/assets/images/beniel-studio.png" alt="Beniel Studio" /></div><div className={styles.dots}>· · ·<br />· · ·<br />· · ·</div></div></div><div className={styles.trustBar}><span>{copy.hero.trust}</span><div>{copy.hero.trustWords.map(word => <b key={word}>{word}</b>)}</div></div></section>
    <section id="productos" className={styles.productsSection}><div className={styles.sectionIntro}><p className={styles.kicker}><i /> {copy.products.eyebrow}</p><h2>{copy.products.title}</h2><p>{copy.products.intro}</p></div><div className={styles.productGrid}>{productMeta.map(([name, image, accent], index) => { const product = copy.products.items[index]; return <article className={`${styles.productCard} ${styles[accent]}`} key={name}><div className={styles.productImage}><img src={image} alt={`${copy.preview} ${name}`} /></div><div className={styles.productContent}><p>{product[0]}</p><h3>{name}</h3><span>{product[1]}</span><div>{product[2].map(tag => <b key={tag}>{tag}</b>)}</div><a href="#contacto">{copy.products.action} <FaArrowRight /></a></div></article>; })}</div></section>
    <section id="servicios" className={styles.servicesSection}><div className={styles.servicesHeader}><div><p className={styles.kicker}><i /> {copy.services.eyebrow}</p><h2>{copy.services.title}</h2></div><p>{copy.services.intro}</p></div><div className={styles.serviceGrid}>{copy.services.items.map(([title, text], index) => { const Icon = serviceIcons[index]; return <article className={styles.serviceCard} key={title}><span>0{index + 1}</span><Icon /><h3>{title}</h3><p>{text}</p><a href="#contacto">↗</a></article>; })}</div></section>
    <section id="proceso" className={styles.processSection}><div className={styles.processVisual}><img src="/assets/images/beniel-studio.png" alt="Beniel Studio" /></div><div className={styles.processCopy}><p className={styles.kicker}><i /> {copy.process.eyebrow}</p><h2>{copy.process.title}</h2><p>{copy.process.intro}</p><ol>{copy.process.items.map(([title, text], index) => <li key={title}><b>0{index + 1}</b><div><h3>{title}</h3><span>{text}</span></div></li>)}</ol></div></section>
    <section id="contacto" className={styles.contactSection}><div className={styles.contactGlow} /><img className={styles.contactLogo} src="/assets/images/beniel-studio.png" alt="Beniel Studio" /><p className={styles.kicker}><i /> {copy.contact.eyebrow}</p><h2>{copy.contact.title}</h2><p>{copy.contact.intro}</p><form className={styles.contactForm} onSubmit={submitContact}><input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder={copy.contact.form.name} aria-label={copy.contact.form.name} /><input required type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} placeholder={copy.contact.form.email} aria-label={copy.contact.form.email} /><textarea required value={form.message} onChange={event => setForm({ ...form, message: event.target.value })} placeholder={copy.contact.form.message} aria-label={copy.contact.form.message} rows={3} /><button className={styles.formButton} type="submit">{copy.contact.form.submit} <FaArrowRight /></button></form><a className={styles.whatsappLink} href="https://wa.me/51910486668" target="_blank" rel="noreferrer"><FaWhatsapp /> {copy.contact.action}</a></section>
    <footer className={styles.footer}><a className={styles.brand} href="#inicio"><img src="/assets/images/beniel-studio.png" alt="" /><span>beniel<span>studio</span></span></a><p>{copy.footer}<a className={styles.creatorLink} href="https://nickledesma.benielstudio.app" target="_blank" rel="noreferrer">{copy.creator}</a></p><span>© {new Date().getFullYear()} Beniel Studio</span></footer>
  </main>;
}
